# Generated by Django 2.2.3 on 2019-07-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('author', 'url', 'publisher'), name='uq_source'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('text', 'translation'), name='uq_translation'),
        ),
    ]
