version: '3'

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=500'
    ports:
      - "5434:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  server:
    build: server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/src
    ports:
      - "8001:8000"
    depends_on:
      - db
  client:
    build: client
    command: ng serve --host 0.0.0.0
    volumes:
      - ./client:/src
    ports:
      - "8000:4200"
    depends_on:
      - server
